config/urls.py
# ----------------------------------------------------------------------------
# Stdlib imports
# ----------------------------------------------------------------------------

from __future__ import absolute_import, unicode_literals


# ============================================================================



# ----------------------------------------------------------------------------
# Core Django imports
# ----------------------------------------------------------------------------

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import views
from django.contrib.sitemaps import GenericSitemap

from .sitemaps import HomeViewSitemap, PublicationSitemap, PostSitemap, AboutSitemap

# ============================================================================



# ----------------------------------------------------------------------------
# Third-party app imports
# ----------------------------------------------------------------------------



# ============================================================================




# ----------------------------------------------------------------------------
# Imports from our apps
# ----------------------------------------------------------------------------



# ============================================================================

sitemaps = {
    'pubs'  : PublicationSitemap,
    'home'  : HomeViewSitemap,
    'posts' : PostSitemap,
    'about' : AboutSitemap,
}




urlpatterns = [
    # Admin site
    url(r'^admin/', include(admin.site.urls)),

    ### User management
    url(r'^users/', include("foton.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Our stuff goes from here

    # ----- PRESENTATION ----- #
    url(r'^', include('foton.presentation.urls', namespace="presentation")),

    # ----- STAFF ----- #
    url(r'^staff/', include("foton.staff.urls", namespace="staff")),

    # ----- PROGRAMS ----- #
    url(r'^programs/', include("foton.programs.urls", namespace="programs")),

    # ----- DEGREE ----- #
    url(r'^degrees/', include("foton.degrees.urls", namespace="degrees")),

    # ----- BLOG ----- #
    url(r'^blog/', include("foton.cicanon.urls", namespace="cicanon")),

    # ----- NOTES ----- #
    url(r'^notes/', include("foton.notes.urls", namespace="notes")),

    # ----- STUDENTS ----- #
    url(r'^students/', include("foton.students.urls", namespace="students")),

    # ----- E-JOURNAL ----- #
    url(r'^e-journal/', include("foton.ejournal.urls", namespace="ejournal")),

    # ----- E-LEARNING ----- #
    url(r'^e-learning/', include("foton.theme.urls", namespace="theme")),

    # ----- PLANNING ----- #
    url(r'^planning/', include("foton.planning.urls", namespace="planning")),

    # ----- PUBLICATION ----- #
    url(r'^publications/', include("foton.publication.urls", namespace="publication")),

    # ----- GALLERY ----- #
    url(r'^galleries/', include('foton.galleries.urls', namespace='galleries')),

    #------ Graduation ------#
    url(r'^certificate/', include('foton.graduation.urls', namespace='graduation')),
    
    url(r'^allianza/', include("foton.elearning.urls", namespace="elearning")),
    
    url(r'^university/', include("foton.universities.urls", namespace="universities")),
    
    url(r'^moocs/', include("foton.moocs.urls", namespace="moocs")),

    # ------ Diplompa ------- #

    # url(r'^diploma/', include("foton.diploma.urls", namespace="diploma")),

    # Rosetta
    url(r'^rosetta/', include('rosetta.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    
    # Sitemaps

    url(r'^sitemap\.xml$', views.index, {'sitemaps': sitemaps}),
    url(r'^sitemap-(?P<section>.+)\.xml$', views.sitemap, {'sitemaps': sitemaps}),



]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception("Bad Request!")}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception("Permission Denied")}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception("Page not Found")}),
        url(r'^500/$', default_views.server_error),
        url(r'^502/$', default_views.server_error),
    ]

foton/cicanon/urls.py
# ----------------------------------------------------------------------------
# Stdlib imports
# ----------------------------------------------------------------------------
from __future__ import absolute_import



# ============================================================================




# ----------------------------------------------------------------------------
# Core Django imports
# ----------------------------------------------------------------------------

from django.conf.urls import url


# ============================================================================




# ----------------------------------------------------------------------------
# Third-party app imports
# ----------------------------------------------------------------------------




# ============================================================================




# ----------------------------------------------------------------------------
# Imports from our apps
# ----------------------------------------------------------------------------

from . import views
from . import feeds


# ============================================================================


urlpatterns = [


	# Categories URLs
	url(

		regex=r"^categories/$",
		view=views.CategoryListView.as_view(),
		name="list-cats"
	),

	url(

		regex=r"^categories/list/$",
		view=views.CategoryPublicListView.as_view(),
		name="public-list-cats"
	),

	url(
		regex=r"^categories/create/",
		view=views.CategoryCreateView.as_view(),
		name="create-cat"
	),

	url(
		regex=r"^categories/(?P<slug>[-\w]+)/update/$",
		view=views.CategoryUpdateView.as_view(),
		name='update-cat'
	),

	url(
		regex=r"^categories/(?P<slug>[-\w]+)/posts/$",
		view=views.CatPostListView.as_view(),
		name='cat-post-list'
	),


	# Posts URLs

	url(
		regex=r"^posts/$",
		view=views.PostListView.as_view(),
		name="list-posts"
	),

	url(
		regex=r"^$",
		view=views.PostPublicListView.as_view(),
		name="public-list-posts"
	),

	url(
		regex=r"^posts/create/$",
		view=views.PostCreateView.as_view(),
		name="create-post"
	),

	url(
		regex=r"^posts/(?P<slug>[-\w]+)/$",
		view=views.PostDetailView.as_view(),
		name="detail-post"
	),

	url(

		regex=r"^posts/(?P<slug>[-\w]+)/detail/$",
		view=views.PostPublicDetailView.as_view(),
		name="public-detail-post"
	),

	url(

		regex=r"^posts/(?P<slug>[-\w]+)/update/$",
		view=views.PostUpdateView.as_view(),
		name="update-post"
	),

	url(
		regex=r"^posts/(?P<pk>[-\w]+)/pub/$",
		view=views.pub_post,
		name="pub-post"
	),

	url(
		regex=r"^posts/feeds/$",
		view=feeds.LastestPost(),
		name="feeds"
	),

]

foton/theme/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse

from foton.theme import  views

urlpatterns = [

	url(
		regex = r'^$',
		view = views.Allianza.as_view(),
		name='allianza'
	),

]

foton/cicanon/models.py
# ----------------------------------------------------------------------------
# Stdlib imports
# ----------------------------------------------------------------------------

from __future__ import absolute_import
import datetime


# ============================================================================




# ----------------------------------------------------------------------------
# Core Django imports
# ----------------------------------------------------------------------------

from django.db import models
from django.utils.translation import ugettext as _
from django.utils.text import slugify as s
from foton.users.models import User
from django.db.models import Model
from django.utils import timezone


# ============================================================================




# ----------------------------------------------------------------------------
# Third-party app imports
# ----------------------------------------------------------------------------




# ============================================================================




# ----------------------------------------------------------------------------
# Imports from our apps
# ----------------------------------------------------------------------------

from django_extensions.db.models import TimeStampedModel


# ============================================================================


class Category(TimeStampedModel, Model):
	"""
		Category Model aims to manage categoories entries in database
	"""
	name = models.CharField(_('Name'), max_length=50)
	slug = models.SlugField(_('Slug'), unique=True)

	class Meta:
		verbose_name 		=_('Category')
		verbose_name_plural = _('Categories')
		ordering 			= ['name']

	def __str__(self):
			return self.name


class Post(TimeStampedModel, Model):
	"""
		Post Model aims to manage post entries in the database
	"""
	title = models.CharField(_('Title'), max_length=250)
	slug = models.SlugField(_('Slug'), unique=True)
	category = models.ForeignKey(Category)
	content = models.TextField(_('Content'))
	picture = models.ImageField(upload_to='image/')
	pub = models.BooleanField(default=False)
	author = models.ForeignKey(User)

	class Meta:
		verbose_name 		=_('Post')
		verbose_name_plural = _('Posts')

	def __str__(self):
		return self.title

foton/cicanon/views.py
# ----------------------------------------------------------------------------
# Stdlib imports
# ----------------------------------------------------------------------------
from __future__ import absolute_import, unicode_literals



# ============================================================================




# ----------------------------------------------------------------------------
# Core Django imports
# ----------------------------------------------------------------------------

from django.views.generic import ListView, DetailView, UpdateView
from django.views.generic.edit import CreateView
from django.core.urlresolvers import reverse_lazy, reverse
from django.contrib.auth.decorators import login_required, permission_required
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.utils.text import slugify


# ============================================================================




# ----------------------------------------------------------------------------
# Third-party app imports
# ----------------------------------------------------------------------------
from braces.views import LoginRequiredMixin, PermissionRequiredMixin



# ============================================================================




# ----------------------------------------------------------------------------
# Imports from our apps
# ----------------------------------------------------------------------------

from .models import Category, Post


# ============================================================================


class CategoryCreateView(
			LoginRequiredMixin,
			PermissionRequiredMixin,
			CreateView):
	"""
		This class allows admin users to create categories
	"""
	model = Category
	success_url = reverse_lazy('cicanon:list-cats')
	template_name = 'cicanon/theme/categories/create.html'
	permission_required = 'users.is_commercial'
	raise_exception = True
	fields = ['name_en','name_fr',]


	def dispatch(self, *args, **kwargs):
		return super(CategoryCreateView, self).dispatch(*args, **kwargs)

	def form_valid(self, form):
		form.instance.slug_en = slugify(form.instance.name_en)
		form.instance.slug_fr = slugify(form.instance.name_fr)
		return super(CategoryCreateView, self).form_valid(form)


class CategoryListView(
			LoginRequiredMixin,
			PermissionRequiredMixin,
			ListView):
	"""
		This class aims to list categories.
	"""
	model = Category
	template_name = 'cicanon/theme/categories/list.html'
	context_object_name = 'cats'
	permission_required = 'users.is_commercial'
	raise_exception = True


class CategoryPublicListView(ListView):
	"""
		This class aims to list categories.
	"""
	model = Category
	template_name = 'cicanon/theme/categories/list-public.html'
	context_object_name = 'cats'
	raise_exception = True


class CategoryUpdateView(
			LoginRequiredMixin,
			PermissionRequiredMixin,
			UpdateView):
	"""
		This class aims to update a category object
	"""
	model = Category
	fields = ['name_en','name_fr']
	success_url = reverse_lazy('cicanon:list-cats')
	template_name = 'cicanon/theme/categories/update.html'
	permission_required = 'users.is_commercial'
	raise_exception = True

	def form_valid(self, form):
		form.instance.slug_en = slugify(form.instance.name_en)
		form.instance.slug_fr = slugify(form.instance.name_fr)
		return super(CategoryUpdateView, self).form_valid(form)


class CatPostListView(DetailView):
	model = Category
	template_name = 'cicanon/theme/categories/detail-public.html'
	context_object_name = 'category'

	def get_context_data(self, **kwargs):
		context = super(CatPostListView, self).get_context_data(**kwargs)
		category = Category.objects.get(slug=self.kwargs['slug'])
		context['posts'] = Post.objects.filter(category = category)
		return context



# ============================================================================


class PostCreateView(
			LoginRequiredMixin,
			PermissionRequiredMixin,
			CreateView):
	"""
		This class allows admin users to create categories
	"""
	model = Post
	success_url = reverse_lazy('cicanon:list-posts')
	template_name = 'cicanon/theme/posts/create.html'
	permission_required = 'users.is_commercial'
	raise_exception = True
	fields = ['title_fr','title_en','category','content_fr','content_en','picture']


	def form_valid(self, form):
		form.instance.author = self.request.user
		form.instance.slug_fr = slugify(form.instance.title_fr)
		form.instance.slug_en = slugify(form.instance.title_en)
		return super(PostCreateView, self).form_valid(form)


class PostListView(
			LoginRequiredMixin,
			PermissionRequiredMixin,
			ListView):
	"""
		This class aims to list categories.
	"""
	model = Post
	 # paginate_by = 2
	template_name = 'cicanon/theme/posts/list.html'
	context_object_name = 'posts'
	permission_required = 'users.is_commercial'
	raise_exception = True


	def get_queryset(self):
		# queryset = super(PostListView, self).get_queryset()
		user = self.request.user
		queryset = user.post_set.all()
		return queryset


class PostDetailView(
			LoginRequiredMixin,
			PermissionRequiredMixin,
			DetailView):
	"""
		This class aims to list categories.
	"""
	model = Post
	template_name = 'cicanon/theme/posts/detail.html'
	context_object_name = 'post'
	permission_required = 'users.is_commercial'
	raise_exception = True


class PostUpdateView(
			LoginRequiredMixin,
			PermissionRequiredMixin,
			UpdateView):
	"""
		This class aims to update a category object
	"""
	model = Post
	fields = ['title_fr','title_en','category','content_fr','content_en','picture']
	success_url = reverse_lazy('cicanon:list-posts')
	template_name = 'cicanon/theme/posts/create.html'
	permission_required = 'users.is_commercial'
	raise_exception = True

	def form_valid(self, form):
		form.instance.slug_fr = slugify(form.instance.title_fr)
		form.instance.slug_en = slugify(form.instance.title_en)
		return super(PostUpdateView, self).form_valid(form)


class PostPublicListView(ListView):
	"""
		This class aims to list categories.
	"""
	model = Post
	template_name = 'cicanon/theme/posts/list-public.html'
	context_object_name = 'posts'
	queryset = Post.objects.filter(pub=True).order_by('-created')


class PostPublicDetailView(DetailView):
	model = Post
	template_name = 'cicanon/theme/posts/detail-public.html'
	context_object_name = 'post'

# ============================================================================


@permission_required('users.is_commercial')
def pub_post(request, pk):
	post = get_object_or_404(Post, pk=pk)
	if post.pub :
		post.pub = False
	else :
		post.pub = True
	post.save()
	return redirect('cicanon:list-posts')

foton/theme/views.py
# @Author: drxos
# @Date:   Saturday, May 14th 2016, 11:24:37 am
# @Email:  sounton@gmail.com
# @Project: Digisity -- University made simple.
# @Last modified by:   drxos
# @Last modified time: Saturday, May 14th 2016, 11:25:02 am
# @License: Copyright (c) Foton IT, All Right Reserved


from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class BackendTemplateView(LoginRequiredMixin, TemplateView):
    redirect_field_name = 'next'
    template_name = 'theme/backend/base.html'

class Allianza(TemplateView):
    template_name = "theme/allianza.html"

foton/cicanon/templates/cicanon/theme/posts/create.html
{% extends "theme/backend/form.html" %}
{% load staticfiles i18n %}

{% block title %}{% trans "Create Post" %}{% endblock title %}

{% block entype %}enctype="multipart/form-data"{% endblock entype %}

{% block value %}{% trans "Create Post" %}{% endblock value %}

foton/cicanon/templates/cicanon/theme/posts/detail-public.html
{% extends "cicanon/theme/base_public.html" %}
{% load staticfiles i18n %}

{% block maintitle %}
	{{ post.title }}
{% endblock maintitle %}


{% block content %}
<hr>
{% if post %}

	<p class="mbl">
	<img src="{{ post.picture.url }}" alt="{{ post.title }}">
	</p>

{% endif %}

<div class="text-justify">
	{% autoescape off %}

		{{post.content}}

	{% endautoescape %}
</div>

<p>
	<div class="info">
		<i class="fa fa-calendar"> {{ post.created }}</i>
		<i class="fa fa-user"> {{ post.author }}</i>
	</div>
</p>

	<hr>

	{% include "cicanon/theme/inc/disqus.html" %}

{% endblock content %}
{% block aside %}

{% endblock aside %}

foton/cicanon/templates/cicanon/theme/posts/detail.html
{% extends "cicanon/theme/base_admin.html" %}
{% load staticfiles i18n thumbnail %}

{% block title %}
	{% if perms.users.is_commercial %}
		{{ post.title }}
	{% else %}
		{% trans "Action Denied!" %}
	{% endif %}

{% endblock title %}

{% block content %}

	<div class="col-md-8">
		{% if perms.users.is_commercial %}

			<p class="mbl">
				{% thumbnail post.picture 650x300 crop as pic %}
				{% if post.picture %}
					<img src="{% static pic.url %}" alt="{{ post.title }}">
				{% endif %}
			</p>

			<div class="text-justify">
				{% autoescape off %}
					{{post.content}}
				{% endautoescape %}
			</div>

			<p>
				<br>
				{{ post.author.get_full_name }} — {{ post.created|date:"l j N o"|capfirst }}
			</p>

			<div>
				{% if not post.pub %}
					<a href="{% url "cicanon:pub-post" post.id %}" class="btn btn-primary">{% trans "Activate" %}</a>
				{% else %}
					<a href="{% url "cicanon:pub-post" post.id %}" class="btn btn-primary">{% trans "Deactivate" %}</a>
				{% endif %}

				<a href="{% url "cicanon:update-post" post.slug %}" class="btn btn-primary" >{% trans "Edit" %}</button>
				</a>

			</div>

		{% else %}
			<span class="em">{% trans "I'm afraid you're kidding! Action Denied!" %}</span>
		{% endif %}
		<br>
	</div>

{% endblock content %}

foton/cicanon/templates/cicanon/theme/posts/list-public.html
{% extends "cicanon/theme/base_public.html" %}
{% load staticfiles i18n %}

{% block maintitle %}{% trans "Posts List" %}{% endblock maintitle %}

{% block content %}
		<hr>
		{% for p in posts  %}

				<a href="{% url "cicanon:public-detail-post" p.slug %}"><h4 class="post-title"><i class="fa fa-angle-right"></i> {{ p.title }}</h4></a>
				<img src="{{ p.picture.url }}" class="post-img" alt="" />
				<p class="post-abstract">
					{% autoescape off %}
						{{ p.content|truncatechars_html:300 }}
					{% endautoescape %}		
				</p>
				<div class="info">
					<i class="fa fa-calendar"> {{ p.created }}</i>
					<i class="fa fa-user"> {{ p.author }}</i>
				</div>
				<a href="{% url "cicanon:public-detail-post" p.slug %}" class="btn btn-large btn-warning">Continue reading</a>

		{% empty %}
			<div class="push">
				{% trans "Sorry! No Post available." %}
			</div>
			
		{% endfor %}

{% endblock content %}

foton/cicanon/templates/cicanon/theme/posts/list.html
{% extends "cicanon/theme/base_admin.html" %}
{% load staticfiles i18n %}

{% block title %}

	{% if perms.users.is_commercial %}
		{% trans "List Post" %}
	{% else %}
		{% trans "Action Denied!" %}
	{% endif %}

{% endblock title %}

{% block content %}
	{% if perms.users.is_commercial %}

	<p class="text-right">
		<a href={% url 'cicanon:create-post' %} class="btn btn-primary">{% trans "Create Post" %}</a>
	</p>

	{% for p in posts  %}

		<div class="">
			{% empty %}
			{% trans "Sorry! No Post available." %}
		</div>
	{% endfor %}

		<div class="dataTable_wrapper">
			<table class="table table-striped table-bordered table-hover" id="dataTables-example">
					<thead>
							<tr>
									<th>{% trans "Posts" %}</th>
									<th>{% trans "Categories" %}</th>
									<th>{% trans "Activation Statut" %}</th>
							</tr>
					</thead>
					{% for p in posts  %}
					<tbody>
							<tr class="odd gradeX">
									<td>{{ p.title }}</td>
									<td>{{ p.category }}</td>
									<td>{{ p.pub }}</td>
									<td class="text-center"><a href={% url 'cicanon:detail-post' p.slug %}><i class="fa fa-plus"></i> Detail</a></td>
									<td class="text-center"><a href={% url 'cicanon:update-post' p.slug %}><i class="fa fa-edit"></i></a></td>
							</tr>
					</tbody>
					{% endfor %}
			</table>
		</div>


	<!-- div class="pagination">
				<span class="step-links">
						{% if page_obj.has_previous %}
								<a href="?page={{ page_obj.previous_page_number }}">previous</a>
						{% endif %}

						<span class="current">
								Page {{ page_obj.number }} of {{ paginator.num_pages }}.
						</span>

						{% if page_obj.has_next %}
								<a href="?page={{ page_obj.next_page_number }}">next</a>
						{% endif %}
				</span>
		</div -->

	{% else %}
		<span class="em">{% trans "I'm afraid you're kidding! Action Denied!" %}</span>
	{% endif %}

{% endblock content %}