config/urls.py
# ----------------------------------------------------------------------------
# Stdlib imports
# ----------------------------------------------------------------------------

from __future__ import absolute_import, unicode_literals


# ============================================================================



# ----------------------------------------------------------------------------
# Core Django imports
# ----------------------------------------------------------------------------

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import views
from django.contrib.sitemaps import GenericSitemap

from .sitemaps import HomeViewSitemap, PublicationSitemap, PostSitemap, AboutSitemap

# ============================================================================



# ----------------------------------------------------------------------------
# Third-party app imports
# ----------------------------------------------------------------------------



# ============================================================================




# ----------------------------------------------------------------------------
# Imports from our apps
# ----------------------------------------------------------------------------



# ============================================================================

sitemaps = {
    'pubs'  : PublicationSitemap,
    'home'  : HomeViewSitemap,
    'posts' : PostSitemap,
    'about' : AboutSitemap,
}




urlpatterns = [
    # Admin site
    url(r'^admin/', include(admin.site.urls)),

    ### User management
    url(r'^users/', include("foton.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Our stuff goes from here

    # ----- PRESENTATION ----- #
    url(r'^', include('foton.presentation.urls', namespace="presentation")),

    # ----- STAFF ----- #
    url(r'^staff/', include("foton.staff.urls", namespace="staff")),

    # ----- PROGRAMS ----- #
    url(r'^programs/', include("foton.programs.urls", namespace="programs")),

    # ----- DEGREE ----- #
    url(r'^degrees/', include("foton.degrees.urls", namespace="degrees")),

    # ----- BLOG ----- #
    url(r'^blog/', include("foton.cicanon.urls", namespace="cicanon")),

    # ----- NOTES ----- #
    url(r'^notes/', include("foton.notes.urls", namespace="notes")),

    # ----- STUDENTS ----- #
    url(r'^students/', include("foton.students.urls", namespace="students")),

    # ----- E-JOURNAL ----- #
    url(r'^e-journal/', include("foton.ejournal.urls", namespace="ejournal")),

    # ----- E-LEARNING ----- #
    url(r'^e-learning/', include("foton.theme.urls", namespace="theme")),

    # ----- PLANNING ----- #
    url(r'^planning/', include("foton.planning.urls", namespace="planning")),

    # ----- PUBLICATION ----- #
    url(r'^publications/', include("foton.publication.urls", namespace="publication")),

    # ----- GALLERY ----- #
    url(r'^galleries/', include('foton.galleries.urls', namespace='galleries')),

    #------ Graduation ------#
    url(r'^certificate/', include('foton.graduation.urls', namespace='graduation')),
    
    url(r'^allianza/', include("foton.elearning.urls", namespace="elearning")),
    
    url(r'^university/', include("foton.universities.urls", namespace="universities")),
    
    url(r'^moocs/', include("foton.moocs.urls", namespace="moocs")),

    # ------ Diplompa ------- #

    # url(r'^diploma/', include("foton.diploma.urls", namespace="diploma")),

    # Rosetta
    url(r'^rosetta/', include('rosetta.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    
    # Sitemaps

    url(r'^sitemap\.xml$', views.index, {'sitemaps': sitemaps}),
    url(r'^sitemap-(?P<section>.+)\.xml$', views.sitemap, {'sitemaps': sitemaps}),



]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception("Bad Request!")}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception("Permission Denied")}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception("Page not Found")}),
        url(r'^500/$', default_views.server_error),
        url(r'^502/$', default_views.server_error),
    ]

foton/cicanon/urls.py
# ----------------------------------------------------------------------------
# Stdlib imports
# ----------------------------------------------------------------------------
from __future__ import absolute_import



# ============================================================================




# ----------------------------------------------------------------------------
# Core Django imports
# ----------------------------------------------------------------------------

from django.conf.urls import url


# ============================================================================




# ----------------------------------------------------------------------------
# Third-party app imports
# ----------------------------------------------------------------------------




# ============================================================================




# ----------------------------------------------------------------------------
# Imports from our apps
# ----------------------------------------------------------------------------

from . import views
from . import feeds


# ============================================================================


urlpatterns = [


	# Categories URLs
	url(

		regex=r"^categories/$",
		view=views.CategoryListView.as_view(),
		name="list-cats"
	),

	url(

		regex=r"^categories/list/$",
		view=views.CategoryPublicListView.as_view(),
		name="public-list-cats"
	),

	url(
		regex=r"^categories/create/",
		view=views.CategoryCreateView.as_view(),
		name="create-cat"
	),

	url(
		regex=r"^categories/(?P<slug>[-\w]+)/update/$",
		view=views.CategoryUpdateView.as_view(),
		name='update-cat'
	),

	url(
		regex=r"^categories/(?P<slug>[-\w]+)/posts/$",
		view=views.CatPostListView.as_view(),
		name='cat-post-list'
	),


	# Posts URLs

	url(
		regex=r"^posts/$",
		view=views.PostListView.as_view(),
		name="list-posts"
	),

	url(
		regex=r"^$",
		view=views.PostPublicListView.as_view(),
		name="public-list-posts"
	),

	url(
		regex=r"^posts/create/$",
		view=views.PostCreateView.as_view(),
		name="create-post"
	),

	url(
		regex=r"^posts/(?P<slug>[-\w]+)/$",
		view=views.PostDetailView.as_view(),
		name="detail-post"
	),

	url(

		regex=r"^posts/(?P<slug>[-\w]+)/detail/$",
		view=views.PostPublicDetailView.as_view(),
		name="public-detail-post"
	),

	url(

		regex=r"^posts/(?P<slug>[-\w]+)/update/$",
		view=views.PostUpdateView.as_view(),
		name="update-post"
	),

	url(
		regex=r"^posts/(?P<pk>[-\w]+)/pub/$",
		view=views.pub_post,
		name="pub-post"
	),

	url(
		regex=r"^posts/feeds/$",
		view=feeds.LastestPost(),
		name="feeds"
	),

]

foton/moocs/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse

from . import  views


urlpatterns = [
	
	url(
		regex = r'(?P<slug>[\w-]+)/details/$',
		view = views.DomainDetailView.as_view(),
		name = 'domain_detail'
	),

	url(
		regex = r'(?P<slug>[\w-]+)/mooc/$',
		view = views.MoocDetailView.as_view(),
		name = 'mooc_detail'
	),

	# url(
	# 	regex = r'^(?P<slug>[-\w]+)/mooc/registration/$',
	# 	view = views.MoocStudentCreateView.as_view(),
	# 	name='mooc-registration'
	# ),

	url(
		regex = r'^(?P<slug>[-\w]+)/mooc/students/$',
		view = views.MoocStudentByProgram.as_view(),
		name='mooc-student'
	),
	url(
		regex = r'^(?P<slug>[-\w]+)/mooc/students/status/(?P<pk>[-\w]+)/$',
		view = views.ActivateMoocStudentView.as_view(),
		name='status-student'
	),

	url(
		regex = r'enroll-course/$',
		view = views.StudentEnrollMoocView.as_view(),
		name = 'student_enroll_mooc'
	),

	url(
		regex = r'my-specialities/$',
		view = views.StudentMoocListView.as_view(),
		name = 'student_mooc_list_view'
	),

	url(
		regex = r'success/registration/$',
		view = views.SuccessRegistration.as_view(),
		name = 'mooc-succes-registration'
	),

	url(
		regex = r'my-specialities/(?P<pk>[\w-]+)/$',
		view = views.StudentMoocDetailView.as_view(),
		name = 'student_mooc_view'
	),

	url(
		regex = r'my-specialities/(?P<pk>[\w-]+)/(?P<id>[\w-]+)/$',
		view = views.StudentMoocDetailView.as_view(),
		name = 'student_mooc_detail_module'
	),

	url(
		regex = r'owner-list/$',
		view = views.MoocByOwnerListView.as_view(),
		name = 'owner-list'
	),
	
	url(
		regex = r'add/$',
		view = views.MoocCreateView.as_view(),
		name = 'mooc-add'
	),
	
	url(
		regex = r'(?P<pk>[-\w]+)/update/$',
		view = views.MoocUpdateView.as_view(),
		name = 'mooc-update'
	),
	
	url(
		regex = r'(?P<pk>[-\w]+)/mooc/module/create/$',
		view = views.MoocModuleUpdateView.as_view(),
		name = 'mooc_module_create'
	),

	url(
		regex = r'(?P<pk>[-\w]+)/mooc/module/$',
		view = views.ModuleListView.as_view(),
		name = 'mooc-modules'
	),
	
	url(
		regex = r'(?P<pk>[-\w]+)/mooc/module/(?P<module_id>\d+)/list/$',
		view = views.ModuleContentListView.as_view(),
		name = 'mooc_module_content_list'
	),

	url(
		regex = r'(?P<pk>[-\w]+)/mooc/module/(?P<module_id>\d+)/content/(?P<model_name>\w+)/create/$',
		view = views.ContentCreateUpdateView.as_view(),
		name = 'mooc_module_content_create'
	),

	url(
		regex = r'(?P<pk>[-\w]+)/module/(?P<module_id>\d+)/content/(?P<model_name>\w+)/(?P<id>\d+)/edit/$',
		view = views.ContentCreateUpdateView.as_view(),
		name = 'mooc_module_content_update'
	),
]

foton/notes/urls.py
# @Author: drxos
# @Date:   Friday, May 6th 2016, 6:03:28 pm
# @Email:  sounton@gmail.com
# @Project: Digisity -- University made simple.
# @Last modified by:   drxos
# @Last modified time: Friday, May 6th 2016, 6:56:12 pm
# @License: Copyright (c) Foton IT, All Right Reserved



from django.conf.urls import url
from django.core.urlresolvers import reverse

from foton.notes import  views


urlpatterns = [
	url(
		regex = r'^$',
		view = views.ClassListView.as_view(),
		name='classes-list'
	),
	url(
		regex = r'classes/(?P<pk>\d+)/$',
		view = views.ClassDetailView.as_view(),
		name='class-detail'
	),
	url(
		regex = r'classes/(?P<pk>\d+)/students/$',
		view = views.StudentDetailView.as_view(),
		name='notes'
	),

	# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
	# ===============================================================
	# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

	url(
		regex = r'classe/list/$',
		view = views.ClassList.as_view(),
		name='list-classes'
	),

	url(
		regex = r'course/list/$',
		view = views.CourseListView.as_view(),
		name='list-course'
	),

	url(
		regex = r'course/create/$',
		view = views.CourseCreateView.as_view(),
		name='create-course'
	),
	url(
		regex = r'course/update/(?P<pk>\d+)/$',
		view = views.CourseUpdateView.as_view(),
		name='update-course'
	),



	url(
		regex = r'classe/(?P<class_pk>\d+)/students/list/$',
		view = views.ClassStudentList.as_view(),
		name='list-student'
	),

	

	url(
		regex = r'classe/(?P<class_pk>\d+)/students/(?P<registred_pk>\d+)/$',
		view = views.StudentNoteList.as_view(),
		name='list-note'
	),

	url(
		regex = r'classe/(?P<class_pk>\d+)/students/(?P<registred_pk>\d+)/note/create/$',
		view = views.NoteCreateView.as_view(),
		name='create-note'
	),

	url(
		regex = r'classe/(?P<class_pk>\d+)/students/(?P<registred_pk>\d+)/note/(?P<pk>\d+)/$',
		view = views.NoteUpdateView.as_view(),
		name='update-note'
	),
]

foton/staff/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.StaffHome.as_view(),
        name='home'
    ),
    url(
        regex=r'^list/$',
        view=views.StaffListView.as_view(),
        name='list-staff'
    ),
    url(
        regex=r'^scolar/add/$',
        view=views.ScolarCreateView.as_view(),
        name='add-scolar'
    ),
    url(
        regex=r'^allianza-admin/add/$',
        view=views.AllianzaAdminCreateView.as_view(),
        name='add-allianza-admin'
    ),
    url(
        regex=r'^commercial/add/$',
        view=views.CommercialCreateView.as_view(),
        name='add-commercial'
    ),
    url(
        regex=r'^scolar/update/(?P<pk>\d+)/$',
        view=views.ScolarUpdateView.as_view(),
        name='update-scolar'
    ),
    url(
        regex=r'^commercial/update/(?P<pk>\d+)/$',
        view=views.CommercialUpdateView.as_view(),
        name='update-commercial'
    ),
    url(
        regex = r'^scolar/active/(?P<pk>\d+)/$',
        view = views.ActivateScolarView.as_view(),
        name='scolar-activate'
    ),
    url(
        regex = r'^scolar/active/(?P<pk>\d+)/$',
        view = views.ActivateAllianzaAdminView.as_view(),
        name='allianza-admin-activate'
    ),
    url(
        regex = r'^commercial/active/(?P<pk>\d+)/$',
        view = views.ActivateCommercialView.as_view(),
        name='activate'
    ),

    url(
        regex = r'year/$',
        view = views.YearListView.as_view(),
        name='list-year'
    ),

    url(
        regex = r'year/create/$',
        view = views.YearCreateView.as_view(),
        name='create-year'
    ),

    url(
        regex = r'year/update/(?P<pk>[-\w]+)/$',
        view = views.YearUpdateView.as_view(),
        name='update-year'
    ),
    
]

foton/theme/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse

from foton.theme import  views

urlpatterns = [

	url(
		regex = r'^$',
		view = views.Allianza.as_view(),
		name='allianza'
	),

]

foton/theme/views.py
# @Author: drxos
# @Date:   Saturday, May 14th 2016, 11:24:37 am
# @Email:  sounton@gmail.com
# @Project: Digisity -- University made simple.
# @Last modified by:   drxos
# @Last modified time: Saturday, May 14th 2016, 11:25:02 am
# @License: Copyright (c) Foton IT, All Right Reserved


from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class BackendTemplateView(LoginRequiredMixin, TemplateView):
    redirect_field_name = 'next'
    template_name = 'theme/backend/base.html'

class Allianza(TemplateView):
    template_name = "theme/allianza.html"

foton/theme/templates/theme/allianza.html
{% extends "theme/default.html" %}
{% load staticfiles i18n %}
{% block title %}{% trans "E-learning" %}{% endblock title %}
{% block maintitle %}  {% trans "Allianza" %}  {% endblock maintitle %}
{% block content %}
<section class="blog">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-8">
            	<img src="{% static "theme/img/allianza.jpg" %}" alt="" class="img-responsive img-thumbnail">
                <hr>
                <p>
             		ALLIANZA est la plateforme d'E-learning d’IRGIB-Africa et de ses partenaires : Universités, Centres de formatons professionnelles et centres de recherches. Elle offre une gamme de formation variée multidisciplinaire qui se regroupe en trois catégories : MOOC, CLMD et FAC, Bachelor, Master et Doctorat.
                </p>
                <div class="panel panel-default">
                    <div class="panel-heading">
                    <h3 class="panel-title">MOOC</h3>
                    </div>
                    <div class="panel-body">
                        <p>
                            Les MOOCs (Massive Oline Open Courses) sont des cours en lignes ouverts et massifs. A cet effet, ils sont gratuits et certifiant. Les MOOCs que nous proposons sont des modules de cours choisis parmi les multitudes qui couvrent nos domaines de compétences : Génies de Procédés de Productions Industrielles, Génies des Technologies de l’Information et de la communication, Génie des Procédés d’Expertises et d’Analyses, Génie du Merchandising, Génie des Procédés De Maintenance et de Fabrication des Equipements Industriels.
                        </p>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                    <h3 class="panel-title">CLMD</h3>
                    </div>
                    <div class="panel-body">
                        <p>
                            Les CLMD (Classique Licence Master et Doctorat) constituent l’ensemble de formations en présentiel que IRGIB-Africa propose et dispense à distance par le truchement de sa plate-forme Allianza. Vous trouverez un peu plus loin une liste des formations disponibles.
                        </p>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                    <h3 class="panel-title">FAC</h3>
                    </div>
                    <div class="panel-body">
                        <p>
                           Les FAC (Formations A la Carte) sont des formations personnalisées. L’étudiant compte tenu de ses projets peut choisir de suivre une FAC afin d’être rapidement opérationnel. Les FAC concernent les professionnels
                        </p>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>
{% endblock content %}

foton/theme/templates/theme/base.html
{% load staticfiles %}
{% load i18n thumbnail %}
{% now "Y" as current_year %}

<!DOCTYPE html>

<html>
<head>
	{% include "seo/seo-base.html" %}
	{% block seo %}{% endblock seo %}
	{% include "theme/inc/head.html" %}
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-84399210-1', 'auto');
	  ga('send', 'pageview');
	</script>
</head>

<body>

	<!-- header -->

<header id="header" class="">
	<div class="mobile">
		<a href="{% url "presentation:about" %}"><img src="{% static "theme/img/mobile.png" %}"></a>
		<div class="name">
			IRGIB AFRICA UNIVERSITY
		</div>
		<div class="dropdown pull-right">
		  <li class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
		    <i class='fa fa-bars'></i>
		  </li>
		  <ul class="dropdown-menu pull-right" aria-labelledby="dropdownMenu1">
			<!-- li><a href="{% url "students:sign-up" %}">{% trans "Admission" %}</a></li-->
			<li><a href="{% url "notes:classes-list" %}">{% trans "Results" %}</a></li>
			<li><a href="{% url "elearning:program-list" %}">{% trans "Allianza" %}</a></li>
			<li><a href= {% url 'cicanon:public-list-posts' %} class="">{% trans "IRGIB Blog" %}</a></li>
			<li><a href="{% url "ejournal:magasines" %}" class="">{% trans "E-Journal" %}</a></li>
			<li><a href= {% url 'publication:list-new' %} class="">{% trans "irgib news" %}</a></li>
			<li><a href= {% url 'publication:list-event' %} class="">{% trans "irgib events" %}</a></li>
			<li><a href={% url 'planning:public-list-planning' %} class="">{% trans "consult planning" %}</a></li>
			{% if user.is_authenticated %}
				{% if perms.users.is_allianza %}
					<li> <a href="{% url 'elearning:student_programs' %}" title=""> {% trans "My Programs" %} </a> </li>
				{% endif %}
				<li> <a href={% url "moocs:student_mooc_list_view" %} >{% trans 'My Sepecialities' %}</a> </li>
			   <li><a href= {% url 'account_logout' %} title="" class="">{% trans "LOGOUT" %}</a></li>
			{% else %}
			   <li><a href= {% url 'account_login' %} title="" class="">{% trans "Login" %}</a></li>
			{% endif %}
		  </ul>
		</div>
	</div>
	{% if user.is_authenticated %}
		<div class="top desktop">
	  	<div class="container">
			<div class="col-md-6">
				{% trans "Welcome to IRGIB AFRICA. You are now connected as " %} {{ user.email }}
			</div>
			<div class="col-md-6 text-right">
				{% if perms.users.is_admin or perms.users.is_scolar or perms.users.is_commercial or perms.users.is_lecturer or perms.users.is_allianzadmin %}
					<a href= {% url 'staff:home' %} >Administration</a>
					<i>|</i>
				{% endif %}
				{% if perms.users.is_allianza %}
					<a href= {% url 'elearning:student_programs' %} >{% trans 'My Programs' %}</a>
					&nbsp;<i>|</i>
				{% endif %}
					<a href="{% url "moocs:student_mooc_list_view" %}" title=""> {% trans "My Sepecialities" %} </a> 
			</div>
	  	</div>
		</div>
	{% endif %}
	<div class="main-header desktop">
		<div class="container">
			<div class="row">
				<div class="col-sm-5 col-md-5 name">
					<img src="{% static "theme/img/svg/logo-off.svg" %}" alt="" class="logo">
				</div>
				<div class="col-sm-5 col-md-2 pull-right search hidden-xs">
					<form action="{% url 'set_language' %}" method="post" class="form-inline">{% csrf_token %}
					    <input name="next" type="hidden" value="{{ redirect_to }}" />
					    <select name="language" class="form-control field">
					        {% get_current_language as LANGUAGE_CODE %}
					        {% get_available_languages as LANGUAGES %}
					        {% get_language_info_list for LANGUAGES as languages %}
					        {% for language in languages %}
					          <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
					                {{ language.name_local }} ({{ language.code }})
					            </option>
					        {% endfor %}
					    </select>
					    <input type="submit" value="{% trans "Ok" %}" class="form-control check"/>
					</form>
				</div>
			</div>
		</div>
	</div>
</header>

<!-- Menu secondaire -->


<div class="sub-nav desktop">
	<div class="container">
		<div class="nav col-sm-8 col-md-9">
			<ul id="">
				<li><a href="{% url "presentation:home" %}">{% trans "Home" %}</a></li>
				<li><a href="{% url "presentation:about" %}">{% trans "Presentation" %}</a></li>
				<li><a href="{% url "students:sign-up" %}">{% trans "Admission" %}</a></li>
				<li><a href="{% url "notes:classes-list" %}">{% trans "Results" %}</a></li>
				<li><a href="{% url "elearning:program-list" %}">{% trans "Allianza" %}</a></li>
			</ul>
		</div>
		<div class="nav col-xs-12 col-sm-4 col-md-3">
			<ul>
				<li><a href="{% url "degrees:bachelor-front-list" %}">{% trans "Bachelor" %}</a></li> &verbar;
				<li><a href="{% url "degrees:masters-front-list" %}">{% trans "Master" %}</a></li>  &verbar;
				<li><a href="#">{% trans "Doctorate" %}</a></li>
			</ul>
		</div>
	</div>
</div>

<!-- Slider -->

{% block slider %}{% endblock slider %}

<!-- Bloc de contenu -->
{% block brief %}{% endblock brief %}

<!-- Last posts -->

{% block main %}
<section class="blog">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-8">
				<div class="news-home">
					{% if GALLERY %}
						<a href={% url 'galleries:list-photos' GALLERY.slug %}><h5>{% trans "Gallery of " %}{{ GALLERY.name }}</h5></a>

						<hr class="aside-hr">

						<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
							<div class="carousel-inner" role="listbox">
								<div class="item active">
									{% thumbnail GALLERY.image 780x350 crop as thumb %}
									<a href={% url 'galleries:list-photos' GALLERY.slug %}><img src="{{ thumb.url }}" class="img-responsive" alt="{{ GALLERY.name }}" /></a>
									<div class="carousel-caption">
										{{ GALLERY.name}}
									</div>
								</div>
								{% for photo in PHOTOS %}
									<div class="item">
										{% thumbnail photo.image 780x350 crop as pic %}
										<a href={% url 'galleries:detail-photo' photo.gallery.slug photo.pk %}><img src="{{ pic.url }}" class="img-responsive" alt="{{ photo.title }}" /> </a>
										<div class="carousel-caption">
											{{ photo.title }}
										</div>
									</div>
								{% endfor %}
							</div>
						</div>
					{% else %}
						<h4> {% trans "La gallerie est actuellement vide !" %} </h4>
					{% endif %}
				</div>
            </div>
				<div class="col-md-4 clo-xs-12 col-sm-12 aside-home">
					{% block aside %}

						<div class="timeline">
							<div class="">
								<h5>{% trans "IRGIB on Twitter" %}</h5>
							</div>
							<hr class="aside-hr">
							<div class="body">
								<a class="twitter-timeline"  href="https://twitter.com/hashtag/irgibafrica" data-widget-id="773189535257726976">Tweets sur #irgibafrica</a>
							</div>
						</div>
						<div class='store desktop'>
							<a href="https://play.google.com/store/apps/details?id=mouhrakib.irg&hl=fr" class="store"><img src="{% static "theme/img/svg/playstore.svg" %}" alt=""></a>
						</div>

					{% endblock aside %}
				</div>
			</div>
		</div>
</section>
{% endblock main %}

<!-- News and events -->

{% block event %}

{% endblock event %}


	<!-- Footer -->

<footer class="desktop">
	<div class="footer">
		<div class="container">
			<h3>{% trans "Helpful Links" %}</h3>
			<hr>
			<div class="row">
				<div class="col-md-3">
					<a href= {% url 'cicanon:public-list-posts' %} class="btn btn-block btn-default">{% trans "our blog" %}</a>
				</div>
				<div class="col-md-3">
					<a href="{% url "ejournal:magasines" %}" class="btn btn-block btn-default">{% trans "E-Journal" %}</a>
				</div>
				<div class="col-md-3">
					<a href= {% url 'publication:list-new' %} class="btn btn-block btn-default">{% trans "irgib news" %}</a>
				</div>
				<div class="col-md-3">
					<a href= {% url 'publication:list-event' %} class="btn btn-block btn-default">{% trans "irgib events" %}</a>
				</div>
				<div class="col-md-3">
					<a href={% url 'planning:public-list-planning' %} class="btn btn-block btn-primary">{% trans "consult planning" %}</a>
				</div>
				<div class="col-md-3">
					<a href="{% url "galleries:list-galleries" %}" class="btn btn-block btn-primary">{% trans "galleries photos" %}</a>
				</div>
				<div class="col-md-3">
					<a href= {% url "presentation:contact" %} class="btn btn-block btn-primary">{% trans "contact us" %}</a>
				</div>
				<div class="col-md-3">
					{% if user.is_authenticated %}
					   <a href= {% url 'account_logout' %} title="" class="btn btn-block btn-primary">{% trans "LOGOUT" %}</a>
					{% else %}
					   <a href= {% url 'account_login' %} title="" class="btn btn-block btn-primary">{% trans "Login" %}</a>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
	<div class="footer-2 desktop">
		<div class="container">
			<div class="row">
				<div class="col-md-10">
					&COPY; 2005-{{ current_year }} {{ SITE_NAME }} - {% trans "All Right Reserved" %}.
				</div>
			</div>
		</div>
	</div>
</footer>
{% include "theme/inc/scripts.html" %}

</body>

</html>